# Tema 2

## 1. Exercitii cu functii

1. Scrieti o functie care determina daca un numar este egal cu suma divizorilor sai, mai putin numarul insusi. 

Exemplu: divizorii lui 6 sunt 1, 2, 3, 6; suma celor mai mici decat 6 este 1+2+3=6=numarul de plecare. Numarul 8 nu este in aceasta situatie: $8 \ne 1+2+4=7$. Folositi aceasta functie pentru a afisa toate numere cu proprietatea ceruta pana la un $n$ dat.

In [1]:
import math
import random
import numpy as np

In [30]:
def check_divisors(number: int) -> bool:
    """
    This function checks if the sum of all the number's divisors(except himself) equals the number
    """
    i: int = 1
    sum_divisors: int = 0
    while i <= number / 2:
        if number % i == 0:
            sum_divisors += i
        i += 1
    if sum_divisors == number:
        return True
    return False

def property(n:int):
    return [x for x in range(1,n) if check_divisors(x)]
print(property(100))

[6, 28]


2. Scrieti o functie care determina daca un sir de caractere - presupus a fi scris cu litere mici - este sau nu palindrom. Un palindrom este un sir de caractere care citit de la dreapta la stanga are acelasi continut ca si citirea de la stanga la dreapta. In functie de valoarea unui indicator boolean `ignore_spaces`, avand valoarea implicita `False`, se vor ignora (elimina) sau nu spatiile. Daca sirul dat ca parametru nu are toate literele mici, se va arunca exceptie; [documentatie exceptii in Python](https://www.w3schools.com/python/gloss_python_raise.asp).

Exemple:

* `is_palindrome('ele fac cafele', ignore_spaces=True)` returneaza `True`; `is_palindrome('ele fac cafele')` returneaza `False`. `is_palindrome('Ele fac cafele')` arunca o exceptie, indiferent de valoarea lui `ignore_spaces`.
*  `is_palindrome('abaac')` returneaza `False`

In [3]:
def is_palindrome(string: str, ignore_spaces: bool = False) -> bool:
    """
    This function returns true if the string parameter is a palindrome.
    If the second parameter is true then all the spaces will pe ignored
    """
    if not str.islower(string):
        raise Exception("Sorry, uppercase letters detected!")
    if ignore_spaces is True:
        string = string.replace(" ", "")
    for index in range(0, int(len(string) / 2)):
        if string[index] != string[-index - 1]:
            return False
    return True


print(is_palindrome("ele fac cafele", True))
print(is_palindrome("ele fac cafele"))
# print(is_palindrome('Ele fac cafele'))
print(is_palindrome("abaac"))

True
False
False


3. Sa se scrie o functie care primeste caile catre doua fisiere de tip text. Despre fiecare fiecare se stie ca are cate un numar pe linie (numarul de linii din fisiere este necunoscut apriori). Functia va returna un tuplu cu: lista de numere care apar in ambele fisiere si diferenta maxima care exista intre numerele din al doilea fisier si numerele din primul fisier. Numerele pot fi cu semn, intregi sau in virgula mobila (functia trebuie sa mearga in orice situatie). Incercati sa folositi functii predefinite din Python (sau NumPy) si collection comprehension.

Exemplu: a.txt contine numerele 1, 2, 3, 4 (cate unul pe linie). b.txt contine 2, 3, 4, 10 (cate un numar pe linie). Functia va returna tuplul `([2, 3, 4], 9)`. Numarul 9 este realizat de 10-1. 

In [32]:
def numbers_from_file(path1: str, path2: str):
    """
    This function returns a list of numbers that are in both files
    and the maximum diference between the numbers from both files
    """
    file1: list = open(path1).read().splitlines()    
    file2: list = open(path2).read().splitlines()
    numberslist1: list = list(map(float, file1))
    numberslist2: list = list(map(float, file2))
    return (
        [x for x in file1 if x in file2],
        max(
            max(numberslist1) - min(numberslist2), max(numberslist2) - min(numberslist1)
        ),
    )


print(numbers_from_file("file1.txt", "file2.txt"))

['1', '-2', '3', '4']
(['3'], 14.0)


4. Sa se scrie o functie `sum_divisors_digits`care preia un numar natural strict pozitiv $n$ si returneaza suma cifrelor divizorilor sai. Intr-o alta functie `black_hole` se apeleaza in mod repetat `sum_divisors_digits` pe numerele rezultate, pana cand se atinge un numar maxim de iteratii (implicit 1000) sau se ajunge la numarul 15. Puteti crea alte  functii auxiliare. 

Exemplul 1: se pleaca de la $n=15$; divizorii sunt $1, 3, 5, 15$; suma cifrelor divizorilor este $1+3+5+1+5=15$, acesta fiind rezultatul apelului `sum_divisors_digits(15)`. Functia `black_hole` se opreste deci dupa un singur apel al functiei `sum_divisors_digits`.

Exemplul 2: se pleaca de la $n=21$; divizorii sunt $1, 3, 7, 21$ iar `sum_divisors_digits(21)` este $1+3+7+2+1=14$; se reia in functia `black_hole` apelul functiei `sum_divisors_digits` pana la epuizarea numarului de apeluri sau potentiala stabilizare in 15.

In [5]:
def sum_digits(n: int):
    """
    This function returns the sum of the number's digits.
    """
    r: int = 0
    while n:
        r, n = r + n % 10, n // 10
    return r


def sum_divisors_digits(n: int):
    """
    This function returns the sum of the number's divisors's digits.
    """
    sum: int = 0
    for d in range(1, n + 1):
        if n % d == 0:
            sum += sum_digits(d)
    return sum

In [6]:
def black_hole(n: int):
    """
    This function runs until the function sum_divisors_digits returns 15 or the loop ends.
    """
    for i in range(1000):
        n = sum_divisors_digits(n)
        if n == 15:
            break
    return n

In [7]:
print(black_hole(15))
print(black_hole(21))
print(black_hole(1))
print(black_hole(0))

15
15
1
0


5. Sa se scrie o functie care primeste doua dictionare si returneaza `True` daca primul dictionar este continut in al doilea si `False` altfel. Spunem ca un dictionar `a` este continut in dictionarul `b` daca toate cheile din `a` se gasesc printre cheile din `b` si toate pentru orice cheie `c` din `a`, `a[c] == b[c]`. Incercati sa folositi functii predefinite din Python (`any, all`), tipuri de date incluse in Python si collection comprehension.   

In [8]:
def second_contains_first(dict1: dict, dict2: dict):
    """
    This function return true if the first dictionary is contained in the second dictionary
    """
    if all(key in dict2.keys() for key in dict1.keys()) == False:
        return False
    return all(dict1[key] == dict2[key] for key in dict1.keys())


dict1 = {
    "A": ".-",
    "B": "-...",
    "C": "-.-.",
    "D": "-..",
    "E": ".",
    "F": "..-.",
    "G": "--.",
    "H": "....",
    "I": "..",
    "J": ".---",
    "K": "-.-",
    "L": ".-..",
    "M": "--",
    "N": "-.",
    "O": "---",
    "P": ".--.",
    "Q": "--.-",
    "R": ".-.",
    "S": "...",
    "T": "-",
    "U": "..-",
    "V": "...-",
    "W": ".--",
    "X": "-..-",
    "Y": "-.--",
    "Z": "--..",
}
dict2 = {
    "A": ".-",
    "B": "-...",
    "C": "-.-.",
    "D": "-..",
    "E": ".",
    "F": "..-.",
    "G": "--.",
    "H": "....",
    "I": "..",
    "J": ".---",
    "K": "-.-",
    "L": ".-..",
    "M": "--",
    "N": "-.",
    "O": "---",
    "P": ".--.",
    "Q": "--.-",
    "R": ".-.",
    "S": "...",
    "T": "-",
    "U": "..-",
    "V": "...-",
    "W": ".--",
    "X": "-..-",
    "Y": "-.--",
    "Z": "--..",
    " ": " ",
    "0": "-----",
    "1": ".----",
    "2": "..---",
}

print(second_contains_first(dict1, dict2))

True


## 2. Exercitii cu NumPy

1. Scrieti o functie care pentru un vector dat $a$ dat, returneaza diferenta de ordinul intai intre elementele sale: $b[i] = a[i+1]-a[i]$. Scrieti apoi o alta functie care face acelasi lucru pentru o matrice, pe linii sau pe coloane.

Exemple: 
* `a = np.array([1, 2, 10, 3])`; `diff1_vector(a)` va returna vectorul NumPy cu continutul `(1, 8, -7)`.
* `a  = np.array([[1, 2, 3], [40, 50, 60]])`; `diff1_mat(a, axis=0)` returneaza o matrice cu o singura linie, `[[39, 48, 57]]`. `diff1_mat(a, axis=1)` returneaza o matrice cu 2x2, `[[1, 1], [10, 10]]`. 

In [9]:
def diff1_vector(a: np.array):
    """
    This function returns the first degree difference of the array's elements.
    """
    return np.array([a[i] - a[i - 1] for i in range(1, len(a))])


print(diff1_vector(np.array([1, 2, 10, 3])))

[ 1  8 -7]


In [10]:
def diff1_mat(a: np.array, axis: int):
    """
    This function returns the first degree difference of the matrix's elements.
    The second parameter indicates the axis on which the difference's evaluated.
    """
    if axis == 0:
        return np.array([a[i] - a[i - 1] for i in range(1, a.shape[0])])
    return np.array([diff1_vector(i) for i in a])


print(diff1_mat(np.array([[1, 2, 3], [40, 50, 60]]), 0))
print(diff1_mat(np.array([[1, 2, 3], [40, 50, 60]]), 1))

[[39 48 57]]
[[ 1  1]
 [10 10]]


2. Sa se scrie o functie care gaseste pozitiile maximelor locale dintr-un vector numpy. Un maxim local este o valoare care are in vecinii imediati (indicele curent $\pm 1$, fara a iesi din vector) valori strict mai mici decat ea. 

Exemplu: `[-1, 3, -7, 1, 2, 6, 0, 1]` -> `[1, 5, 7]`.

In [16]:
def local_maxims(l: np.array):
    """
    This function returns the local maxims in the array
    """
    result = [i for i in range(1, len(l) - 1) if l[i - 1] < l[i] and l[i + 1] < l[i]]
    if len(l) > 1:
        if l[len(l) - 2] < l[len(l) - 1]:
            result += [len(l) - 1]
        if l[0] > l[1]:
            result = [1] + result
    return np.array(result)
    
print(local_maxims(np.array([-1, 3, -7, 1, 2, 6, 0, 1])))
print(local_maxims(np.array([1, 2, 3, 4, 3, 5, 2, 4, 8, 8, 8, 9])))

[1 5 7]
[ 3  5 11]


3. Pentru un vector NumPy dat, sa se calculeze toate ferestrele de o anumita lungime, cu o anumita dilatare. Lungimea unei ferestre inseamna numarul de elemente din vectorii rezultati, dilatare reprezinta peste cate elemente vecine se sare in construirea unei "ferestre".

Exemple:
* v = np.arange(20), win_len=4, dilation=1 -> [0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], ...[16, 17, 18, 19]
* v = np.arange(20), win_len=3, dilation=2 -> [0, 2, 4], [1, 3, 5], ..., [15, 17, 19]

Valorile implicite pentru `win_len` si `dilation` sunt 3, respectiv 1. Veti verifica in cadrul functiilor daca: `0 < win_len <= numarul de elemente din vector`, `dilation` > 0 si daca pentru vectorul de intrare, `win_len` si `dilation` date rezulta macar o fereastra; daca vreuna din aceste conditii nu se indeplineste, nu se executa restul functiei si se arunca exceptie (se pot folosi assertiuni sau aruncari de exceptii). Rezultatul se va da ca un tablou cu `win_len` coloane.

In [18]:
def vector_windows(v: np.array, win_len: int = 3, dilation: int = 1):
    """
    This function returns a 2D numpy array with lines that have the length of win_len and
    contains elements that have a difference of dilation of the index's between them. 
    """
    if not (0 < win_len <= len(v) and dilation > 0):
        raise Exception("Sorry, the input is not valid")
    return np.array([[v[i + j * dilation] for j in range(win_len)] for i in range(len(v) - (win_len - 1) * dilation)])
    vector_windows()
print(vector_windows(np.arange(20)))

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]]


4. Descarcati setul de date Wine descris la 'http://archive.ics.uci.edu/ml/datasets/Wine', fisierul `wine.data`, si incarcati-l intr-o matrice NumPy, folosind np.genfromtxt. Alegeti aleator 35 de pozitii din cadrul matricei de valori, setati pe aceste pozitii NaN. Construiti o functie care, primind la intrare o matrice, returneaza o colectie cu indicii de linii respectiv de coloane in care se gasesc valori Na, precum si matricea 'corectata': valorile NaN se umplu cu o valoare implicita data ca parametru al functiei dvs. 

In [19]:


def Nan_to_value(matrix:np.array,value:int=100):
    """
    This function returns a list of NaN's indexes in the matrix and the matrix with the NaN
    value replaced with the second parameter value.
    """
    list_of_nan_indexes:np.array=np.argwhere(np.isnan(matrix))
    matrix[np.isnan(matrix)]=value
    return (list_of_nan_indexes, matrix)

matrix=np.genfromtxt("wine.data", delimiter=",")
choice = np.random.choice(matrix.size, 35, replace=False)

rows, cols = np.unravel_index(choice, matrix.shape)
matrix[rows, cols] = np.nan

result=Nan_to_value(matrix)
print(result[0])
print(result[1])

[1334  667  916 1417  307 2434   87 1020   44  276 1169 1772  677  703
 1803 2312 2194 2337 1425 1290  957 1051 2384  277  723 1253 1137   69
 1550 1136 2021   18  262 1455 1233]
[[  1   4]
 [  3   2]
 [  4  13]
 [  6   3]
 [ 18  10]
 [ 19  10]
 [ 19  11]
 [ 21  13]
 [ 47   9]
 [ 48   5]
 [ 50   3]
 [ 51   9]
 [ 65   6]
 [ 68   5]
 [ 72  12]
 [ 75   1]
 [ 81   2]
 [ 81   3]
 [ 83   7]
 [ 88   1]
 [ 89   7]
 [ 92   2]
 [ 95   4]
 [101   3]
 [101  11]
 [103  13]
 [110  10]
 [126   8]
 [128  11]
 [144   5]
 [156  10]
 [165   2]
 [166  13]
 [170   4]
 [173  12]]
[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


5. Se da un vector `v` de numere floating point, un numar floating point `x` si un numar intreg `k>0`, `k<=len(v)`. Sa se scrie o functie care determina pozitiile celor mai apropiate `k` valori din `v` fata de `x` (k nearest neighbors, 1d).

In [24]:
 def k_nearest_neighbors(v:np.array,x:float,k:int):
        """
        This function returns the k nearest neighbours of x in the v array.
        """
        if k<=0 or k>len(v):
            raise Exception("k parameter must be a value between 0 and the length of the array")
        distance_list=[(index,abs(element-x)) for index,element in enumerate(v)] 
        return [sorted(distance_list, key=lambda x: x[1])[index][0] for index in range(k)]
    
print(k_nearest_neighbors(np.array([7.45,8.42,2.62,6.1]),7.45,2))

[1, 2]
