In [150]:
import numpy as np
print(f'NumPy version: {np.__version__}')

import pandas as pd
print(f'Pandas version: {pd.__version__}')

import sklearn as sk
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import CountVectorizer
print(f'Sklearn version: {sk.__version__}')

#NumPy version: 1.20.1
#Pandas version: 1.2.3
#Sklearn version: 0.24.1

NumPy version: 1.20.1
Pandas version: 1.2.3
Sklearn version: 0.24.1


In [151]:
dataset = pd.read_csv('data/SMSSpamCollection.', sep = '\t', names=["label", "sms"])

In [152]:
text_X = dataset["sms"].values
text_Y = dataset["label"].values

In [153]:
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(text_Y.reshape(-1,1))
Y = enc.transform(text_Y.reshape(-1,1)).toarray()

In [159]:
Vect = CountVectorizer(max_features=1500, min_df=5, max_df=0.7)
X = vect.fit_transform(text_X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
